global.scriptArray = [
[spr_Chaos_Icons, 0, "You awake?"],
[spr_Verdali_Icons, 0, "Yeah--"],
[spr_Verdali_Icons, 0, "Wait."],
[spr_Verdali_Icons, 1, "What are you?"],
[spr_Verdali_Icons, 1, "And why are you coming out of my chest?"],
[spr_Chaos_Icons, 1, "!"],
[spr_Chaos_Icons, 2, "You... you're kidding, right?"],
[spr_Chaos_Icons, 2, "You just agreed to be my Vessel less than a minute ago."],
[spr_Verdali_Icons, 2, "\n"],
[spr_Chaos_Icons, 2, "There was a bunch of shining lights..."],
[spr_Verdali_Icons, 2, "\n"],
[spr_Chaos_Icons, 2, "This whole transformation thing... ?"],
[spr_Verdali_Icons, 2, "\n"],
[spr_Chaos_Icons, 2, "You've now got the fragments of a\ndivine being entwined in your soul???"],
[spr_Verdali_Icons, 1, "That's not ringing any bells..."],
[spr_Verdali_Icons, 0, "... Who am I again?"],
[spr_Chaos_Icons, 5, "Oh for... *sigh*"],
[spr_Chaos_Icons, 0, "Your name is Verdali. My name is Chaos."],
[spr_Chaos_Icons, 0, "I can explain everything later."],
[spr_Chaos_Icons, 0, "Right now we need to get off of this battlefield."],
[spr_Verdali_Icons, 1, "And why should I go with you?"],
[spr_Chaos_Icons, 5, "Look, I'm the one that's stuck with you."],
[spr_Chaos_Icons, 0, "But if you want to die\nand turn into one of those monsters"],
[spr_Chaos_Icons, 0, "be my guest."],
[spr_Verdali_Icons, 1, "*sigh*"],
[spr_Verdali_Icons, 0, "Fine. Let's get going."],
];